name: Test Application

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: [3.8, 3.9, "3.10", "3.11"]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest streamlit
    
    - name: Test imports
      run: |
        python -c "import streamlit; import PIL; import numpy; import scipy; print('✅ All imports successful')"
    
    - name: Check Streamlit app syntax
      run: |
        python -m py_compile app.py
        echo "✅ App syntax check passed"
    
    - name: Test app runs without errors
      run: |
        timeout 30s streamlit run app.py --server.headless true --server.port 8501 || true
        echo "✅ App startup test completed"
